Repository modern-agile-team/quiz-game-io-front, pull requests merged in 2025-09, with the labels that each got.

#69 chore: pr size label 액션 추가 #68
  .github/workflows/pr-size-label.yml
Labels: size/So Cute🥚

#75 [#74] 커밋 린트 수정
  commitlint.config.cjs
  scripts/commit-helper.js
Labels: size/Cute🐣

#76 [#73] lobby user list query
  .yarn/install-state.gz
  src/apps/lobby/components/ParticipantCard.tsx
  src/apps/lobby/components/layouts/DesktopLayout.tsx
  src/apps/lobby/components/layouts/MobileLayout.tsx
  src/apps/lobby/data/mockData.ts
  src/apps/lobby/index.tsx
  src/apps/lobby/types/index.ts
  src/apps/lobby/utils/helpers.ts
  src/shared/service/api/client/index.ts
  src/shared/service/api/query/lobby.ts
Labels: size/Cute🐣

#80 chore: 코드젠
  .yarn/install-state.gz
  src/lib/orval/_generated/quizzesGameIoBackend.schemas.ts
  src/lib/orval/_generated/quizzesGameIoBackend.ts
  src/lib/orval/spec.json
Labels: size/Cute🐣

#81 [#78]: 내 정보 불러오기 api 연동
  src/apps/room/[id]/data/mockData.ts
  src/apps/room/[id]/index.tsx
  src/shared/service/api/query/accounts.ts
  src/shared/service/api/query/index.ts
Labels: size/Cute🐣

#84 [#82] user list 불러오는 로직 변경
  src/apps/lobby/index.tsx
  src/shared/service/api/query/index.ts
  src/shared/service/api/query/lobby.ts
Labels: size/So Cute🥚

#85 [#83] 의존성 설치 후 .pnp.cjs와 VSCode SDK 설정 업데이트
  .pnp.cjs
  .vscode/settings.json
  .yarn/install-state.gz
  .yarn/sdks/eslint/bin/eslint.js
  .yarn/sdks/eslint/lib/api.js
  .yarn/sdks/eslint/lib/config-api.js
  .yarn/sdks/eslint/lib/types/config-api.d.ts
  .yarn/sdks/eslint/lib/types/index.d.ts
  .yarn/sdks/eslint/lib/types/rules.d.ts
  .yarn/sdks/eslint/lib/types/universal.d.ts
  .yarn/sdks/eslint/lib/types/use-at-your-own-risk.d.ts
  .yarn/sdks/eslint/lib/universal.js
  .yarn/sdks/eslint/lib/unsupported-api.js
  .yarn/sdks/prettier/bin/prettier.cjs
  .yarn/sdks/prettier/index.cjs
  .yarn/sdks/typescript/bin/tsc
  .yarn/sdks/typescript/bin/tsserver
  .yarn/sdks/typescript/lib/tsc.js
  .yarn/sdks/typescript/lib/tsserver.js
  .yarn/sdks/typescript/lib/tsserverlibrary.js
  .yarn/sdks/typescript/lib/typescript.js
  src/lib/orval/_generated/quizzesGameIoBackend.schemas.ts
Labels: size/Hell🦅
